<div class="alert alert-block alert-info">
<h2> 2. Complex Data Types (Lists, Tuples, & Dictionaries) & Stat Modelling with NumPy</h2><br>

</div>

<div class="alert alert-block alert-info">
<h2> Lists and Tuples</h2><br>
<p>Both lists and tuples are collections of data values. The major difference between the two is that lists are changeable, while tuples cannot be mutated. Tuples are like read-only data.</p><br>

<p><b>Syntax of lists</b>: values are entered into square brackets [ ]. String values are entered with quotes, while numeric values do not need quotes.</p>  
<p>
__Example__:   
myList = ['heavy metal', 'Germany', 'jazz', -50]</p><br>
<p><b>Syntax of tuples</b>: values are entered into parentheses ( ). </p><br>
<p>
__Example__:   
myTuple = ('heavy metal', 'Germany', 'jazz', -50)</p>
</div>

In [1]:
# Let's create the musicList variable to store data on the dominating music genres of some festival in 1999.
# Assign real data about Coachella(https://www.billboard.com/articles/columns/music-festivals/6538604/coachella-history-genre-by-year).

musicList = ['electronic', 'hip-hop', 'indie music', 1999]
musicList

['electronic', 'hip-hop', 'indie music', 1999]

In [2]:
# Lists can be expanded and changed, while tuples cannot.
# Let's create a tuple variable with the same values as myList first.

myTuple = ('electronic', 'hip-hop', 'indie music', 1999)
myTuple

('electronic', 'hip-hop', 'indie music', 1999)

In [3]:
# Data values in myTuple are the same as in a list, but the data container is essentially different.
# You can test how they differ by trying to manipulate any of these data types with the list method - that is, append().

musicList.append('alternative')
print(musicList)

myTuple.append('alternative')
print(myTuple)

# The output gives the result for expanded myList, but it throws an error for myTuple because tuples cannot be mutated.

['electronic', 'hip-hop', 'indie music', 1999, 'alternative']


AttributeError: 'tuple' object has no attribute 'append'

In [4]:
# You can count how many items a list (and a tuple) contains with len(). 

len(musicList)

5

In [5]:
# You can check what data item sits in a sequence by its index position. See more on index position in Lesson 1.
# Remember that index position starts from 0, NOT from 1. This means that the 1st item in a list sits in 0 position.
# The 1st item in 0 position in musicList is 'electronic', but the 2nd item 'hip-hop' is in 1 position: 

print(musicList[0])
print(musicList[1])

electronic
hip-hop


In [6]:
# You may expand your lists by inserting new value at the exact position that you want with insert().
# Let's insert the numeric value of 2000 at the end of the list to add another year of the festival.

musicList.insert(4, 2000)
musicList

['electronic', 'hip-hop', 'indie music', 1999, 2000, 'alternative']

In [7]:
# We will learn more about loops next week. But let's start by getting some flavour of what loops can do.
# Let's say we want to print out every data item in a list without referring to each of them by index position.
# Iterate over each item in the musicList and print each item with the phrase 'I love' before that item.

for x in musicList:     
    print("I love", x)
    
    
# x is an arbitrary reference to each item in a defined list. 
# Instead of 'x', you may use any character or word or phrase to run loops, but keep it simple and short.

I love electronic
I love hip-hop
I love indie music
I love 1999
I love 2000
I love alternative


In [8]:
# If you do not loop through the list and print out the phrase 'I love' with the whole musicList, you get the following

print("I love", musicList)

I love ['electronic', 'hip-hop', 'indie music', 1999, 2000, 'alternative']


<div class="alert alert-block alert-info">
<h2> Dictionaries</h2><br>
<p>Dictionaries consist of keys and values. Think of dictionaries as pro-table format where keys are as if headings and values are as if information points under those headings. Keys are unique, but the values assigned to one key can be many.</p><br> 

<p><b>Syntax of dictionaries</b>: keys and values are entered into curly brackets { } with the colon : separating them</p>  

__Example__:   
Castle_Repository = {'France': 6500, 'Germany': 25000, 'Wales': 33}
</div>

In [9]:
musicDict = {'Tom': 'heavy metal', 'Lilly': 'punk rock', 'Avni': 'classical music'}
musicDict

{'Tom': 'heavy metal', 'Lilly': 'punk rock', 'Avni': 'classical music'}

In [10]:
#Both keys and values could be numeric or textual.

colorDict = {1: 'green', 2: 'yellow', 3: 'skyblue'}
colorDict

{1: 'green', 2: 'yellow', 3: 'skyblue'}

In [11]:
# You can query dictionaries by keys to find the values assigned to a specific key.

print(musicDict['Avni'])
print(colorDict[1])

# If you want to see the output of both variables in this case, use the function print(). 
# Otherwise, only the last variable in the code cell - that is, colorDict[1] - will be output here.

classical music
green


In [12]:
# Like lists, dictionaries are mutable. This means that we can modify them.
# We can update their values, for example:

colorDict = {1: 'green', 2: 'yellow', 3: 'skyblue'}
print(colorDict)

colorDict[1]='red'
print(colorDict)

{1: 'green', 2: 'yellow', 3: 'skyblue'}
{1: 'red', 2: 'yellow', 3: 'skyblue'}


In [13]:
# We can delete the key-value pairs of our choosing by specifying the key:

del colorDict[2]
print(colorDict)

# OR by specifying the value:

del musicDict['Lilly']
print(musicDict)

{1: 'red', 3: 'skyblue'}
{'Tom': 'heavy metal', 'Avni': 'classical music'}


In [14]:
# We've been modifying our dictionaries a bit, so let's check how many items are left in musicDict after all.

len(musicDict)

2

In [15]:
# Let's add new data to musicDict. The way is the same as updating dictionaries. 
# If the key exists, the value will be update; if the key is new, the value will be added

musicDict['Ugne'] = 'jazz'
musicDict

{'Tom': 'heavy metal', 'Avni': 'classical music', 'Ugne': 'jazz'}

In [16]:
# Dictionaries have their methods, e.g. get().
# Methods are functions that go together with specific objects. Think of methods as verbs that tell us what objects do.
# Let's use our first dictionary created in this tutorial - that is, musicDict.
# Like any Python dictionary, musicDict can get us values by their corresponding keys.

musicDict.get('Avni')

'classical music'

In [17]:
# Dictionaries can be merged. First, let's create two variables that contain dictionaries.

primaryColors = {1: 'red', 2: 'yellow', 3: 'blue'}
print(primaryColors)

secondaryColors = {4: 'orange', 5: 'green', 6: 'purple'}
print(secondaryColors)

{1: 'red', 2: 'yellow', 3: 'blue'}
{4: 'orange', 5: 'green', 6: 'purple'}


In [18]:
# Let's merge primaryColors with secondaryColors.

allColors = {**primaryColors, **secondaryColors}
allColors

{1: 'red', 2: 'yellow', 3: 'blue', 4: 'orange', 5: 'green', 6: 'purple'}

In [19]:
# The dictionary method get() is a quick way to search a dictionary by keys to retrieve their values.

print(allColors.get(5))

# Note that the numeric keys here are not the same as index position used to search lists.

# Try it out by entering other keys.

green


<div class="alert alert-block alert-info">
<h2>NumPy Arrays</h2>
<ul>
<li>Now let's explore how dictionaries can be useful in statistical modelling and data manipulation.</li>
<li>Python does not have built-in support for arrays. Instead, it offers you to work with lists. Yet lists are limited.</li>
<li>Arrays and lists share some similarities, but the difference between the two is key to what you can do to data.</li>
<li>On the similarity side, arrays and lists can both 1) store data; 2) store any type of data (numbers, characters etc); 3)be indexed and iterated through.</li>
<li>However, they do not serve the same purpose. NumPy arrays are the most important data type for arithmetic data manipulation, while most of arithmetic manipualtion cannot be performed on lists as you can see below.</li>
</ul>
</div>

In [20]:
# Lists do not have to be declared. It's enough to create a variable by using list syntax and assingning values.

myList = [4, 8, 12]
myList

[4, 8, 12]

In [21]:
# But see what happens when you try to perform some math, e.g. divide each value by 2

myList = myList/2
print(myList)

TypeError: unsupported operand type(s) for /: 'list' and 'int'

In [22]:
# That's right, the code throws an error!
# Unlike lists, NumPy arrays have to be declared by using the keyword 'array'. 
# Array syntax requires that you put lists in parenthesis.
# Let's take the values of myList and create an array, but first import the numpy package to use the functionality of arrays. 
# Use the shorthand 'np' to make it quicker to use the methods specific to numpy.

import numpy as np
myArray = np.array([4, 8, 12])
myArray

array([ 4,  8, 12])

In [23]:
# Now let's try to perform the same division as we tried to do it with myList

myArray = myArray/2
print(myArray)

[2. 4. 6.]


In [24]:
# myArray above is an example of 1-dimensional array.
# The beauty with Numpy arrays is that we can create two- and multi-dimensional arrays to work with more complex data.
# We can put together two lists to create 2-dimentional array, for example:

myNewArray = ([4, 8, 12, 16, 20, 2, 50], [5, 7, 30, 4, 1, 15, 100])
myNewArray

# Think of it as a table with two rows of values

([4, 8, 12, 16, 20, 2, 50], [5, 7, 30, 4, 1, 15, 100])

<img src="array.JPG">

In [25]:
# We can calculate the mean of values contained in a numpy array.

np.mean(myNewArray)

19.571428571428573

In [26]:
# We can search for the smallest value in an array.

np.min(myNewArray)

1

In [27]:
# We can identify the biggest value, no matter how big is our data.

np.max(myNewArray)

100

In [28]:
# If axis is set to 1, it will return values by row.
# Thus we can pick up the lowest values in each row of our 2-dimensional array.

np.min(myNewArray, axis=1)

array([2, 1])

<img src="arrayTwo.JPG">

In [29]:
# If axis is set to 1, it will return values by column.
# The code below will return the smallest values found in each column.

np.min(myNewArray, axis=0)

array([ 4,  7, 12,  4,  1,  2, 50])

<img src="arrayThree.JPG">

In [30]:
# Import the csv ('comma-separated values') file called 'winter.csv'.
# The numpy method to import structured data is genfromtxt().

winter1 = np.genfromtxt("winter.csv", delimiter =",")

# The alternative function is loadtxt(), which is faster but, unlike genfromtxt(), does not take into account missing values.

In [31]:
print(winter1)

[[   nan    nan    nan    nan]
 [2017.    12.4   14.3   16.6]
 [2018.    16.3   22.2   20.1]]


In [32]:
# The csv file contains mixed data -  both textual and numeric. As you can see, the textual data has been replaced with 'NaN'.
# We can either remove the rows with textual data OR we can force all data be displayed in the output.
# If we are confident that the textual data, especially in the header, is not essential, we can remove it:

winter2 = np.genfromtxt("winter.csv", delimiter=",", skip_header=1)

print(winter2)

[[2017.    12.4   14.3   16.6]
 [2018.    16.3   22.2   20.1]]


In [33]:
# To print out all mixed data, you may need to set dtype to None as below.

winter3 =  np.genfromtxt("winter.csv", delimiter=",", dtype=None)
print(winter3)

# The output may contain 'b' before each data value. 
# np.genfromtxt operate in byte mode, which is the default string type in Python 2. 
# But Python 3 uses unicode, and marks bytestrings with this character 'b'.

[[b'Year' b'Dec' b'Jan' b'Feb']
 [b'2017' b'12.4' b'14.3' b'16.6']
 [b'2018' b'16.3' b'22.2' b'20.1']]


C:\Users\1veln\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  This is separate from the ipykernel package so we can avoid doing imports until


In [34]:
# If you set dtype argument to 'str', it gives the cleanest display.

winter3 =  np.genfromtxt("winter.csv", delimiter=",", dtype=str)
print(winter3)

[['Year' 'Dec' 'Jan' 'Feb']
 ['2017' '12.4' '14.3' '16.6']
 ['2018' '16.3' '22.2' '20.1']]


In [35]:
# We can slice off a piece of numpy arrays by index position as we did it with lists and tuples.
# If we set the slicer to [2], it will return the third row.

print(winter3[2])

['2018' '16.3' '22.2' '20.1']


In [36]:
# We may save the numpy array as csv or text files.
# fmt argument specified formatting options. By default numbers will be stored in float format.
# %d value will store numbers as integers, while %s saves them as strings.

np.savetxt("winter3.csv", winter3, delimiter=",", fmt='%s')

# Alternative way is to use winter3.tofile() method, yet it may cause various formatting problems.
# More on saving arrays in external files see: https://thispointer.com/how-to-save-numpy-array-to-a-csv-file-using-numpy-savetxt-in-python/

<div class="alert alert-block alert-info">
    <h1>pandas and DataFrames</h1>
    <p>The pandas data frame is an easy-to-query table-like structures consisting of rows and columns. They can be created by loading the data from the external, existing storage like a database, SQL or CSV files. But the pandas Data Frame can also be created from the lists, dictionary, etc.</p>
 </div>

In [37]:
# We may read a cvs file as DataFrame by using the pandas library.
# Import pandas under the alias 'pd' for quicker coding.

import pandas as pd

# You may check the version of pandas, and ny other module, by using double underscore as below:

pd.__version__

'0.24.2'

In [38]:
# Create a variable pdWinter to store the csv file as DataFrame.

pdWinter = pd.read_csv("winter.csv", sep=",")

# Print out the output of your variable. As you can see, pandas and their DataFrame cope nicely with outputting mixed data.

pdWinter

Year   Dec   Jan   Feb
0  2017  12.4  14.3  16.6
1  2018  16.3  22.2  20.1

In [39]:
# Add a new row to pdWinter to include the forecast for winter 2019.
# First we need to define the data for the new row we want to add. This is where dictionaries come in handy.

row = pd.Series({'Year':2019,'Dec':9,'Jan':7,'Feb':11},name=2)

# Then use the append() method to add the row variable to pdWinter.

Winter2017_2019 = pdWinter.append(row)

Winter2017_2019

Year   Dec   Jan   Feb
0  2017  12.4  14.3  16.6
1  2018  16.3  22.2  20.1
2  2019   9.0   7.0  11.0

In [40]:
# We can also add new columns to the existing data in DataFrames. This time we want to add temperatures for spring months.
# We  can use pandas-specific method assign() and lists.

Winter_Spring = pdWinter.assign(March=[15.3, 16.7], April=[17.1, 17.5], May=[24.2, 20])

Winter_Spring

Year   Dec   Jan   Feb  March  April   May
0  2017  12.4  14.3  16.6   15.3   17.1  24.2
1  2018  16.3  22.2  20.1   16.7   17.5  20.0

In [41]:
# We can dinally export the expanded data from DataFrame to a csv file.
# The argument index=False will prevent from saving the index column into an external file.

Winter_Spring.to_csv("winter_spring.csv", index=False)

In [42]:
# We can convert pandas' DataFrames to Numpy arrays as below:

npTemps = np.array(Winter_Spring)

print(npTemps)

[[2017.    12.4   14.3   16.6   15.3   17.1   24.2]
 [2018.    16.3   22.2   20.1   16.7   17.5   20. ]]


<div class="alert alert-block alert-success">
<h2>Over to You</h2><br>
<ul><li>Find some structured data published publicaly online. You may wish to work with, for example, immigration stats as published on www.gov.uk. You may, for example, merge data from separate spreadsheets to get a more comparative view on bigger data.</li>
<li>You may work with NumPy arrays or pandas' DataFrames, or a combination of both.</li>
<li>Calculate the median, mean, minimum and maximum values of your data. You may want to experiment more with slicing and dicing your data.</li>
<li>Draw some conclusions about the underlying patterns of your data.</li>
<li>Create a new data variable at the end and save it in the external csv file.</li>
<li>Document your data wranggling with comments in the code cells. Use the markdown cells to explain where you csv file(s) come from and to comment of your findings. </li>
<li>Save your Jupyter Notebook as 'Lesson2.ipynb' and zip it with all the relevant Excel files (the ones that you download from an external link and the one that you create in the end) in the file called 'Homework2.zip'.</li></ul><br>
<h3>Submit the zipped file via the designated area on KEATS by 4pm on 21st November 2019.</h3>
</div>